# Generated by Django 4.2.1 on 2023-06-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bposts', '0003_comment_created_at_comment_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
