# Generated by Django 4.2.1 on 2023-07-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_created_task_description_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
