# Generated by Django 4.2.1 on 2023-08-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('aboutme', '0001_initial'), ('aboutme', '0002_profile_description'), ('aboutme', '0003_remove_profile_resume'), ('aboutme', '0004_alter_profile_description'), ('aboutme', '0005_delete_profile')]

    initial = True

    dependencies = [
    ]

    operations = [
    ]
