# Generated by Django 4.2.1 on 2023-06-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_profile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resume',
        ),
    ]
