# Generated by Django 4.2.1 on 2023-06-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0003_remove_profile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
